# Rotary Encoders aktivieren
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Bluetooth-Sendeleistung optimieren & Deep Sleep nach 15 min
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# RGB Underglow standardmäßig beim Start ausschalten
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n

# Falls dein Build auch Backlight-Flags nutzt:
CONFIG_ZMK_BACKLIGHT=n
